#source 'https://github.com/CocoaPods/Specs.git'
source 'https://cdn.cocoapods.org/' 
platform :ios, '9.0'
inhibit_all_warnings!

targetsArray = ['DeveloperArchitecture']

targetsArray.each do |t|
    target t do
        use_frameworks!

        pod 'ReachabilitySwift'
#        pod 'MLeaksFinder'
    end
end

