#source 'https://github.com/CocoaPods/Specs.git'
source 'https://cdn.cocoapods.org/'
platform :ios, '9.0'
inhibit_all_warnings!

targetsArray = ['DevelopArchitecture']

targetsArray.each do |t|
    target t do
#        pod 'socket.IO'
        pod 'MLeaksFinder'
    end
end

